services:
 postgres:
  image: postgres:18-alpine
  ports:
   - 5432:5432
  volumes:
   - pgdata:/var/lib/postgresql
  environment:
   - POSTGRES_PASSWORD=postgres
   - POSTGRES_DB=postgres
  healthcheck:
   test: ["CMD", "pg_isready", "-h", "127.0.0.1", "-U", "postgres", "-d", "postgres"]
   interval: 2s
   timeout: 5s
   retries: 30
   start_period: 10s

volumes:
 pgdata:
